username = input("Enter an username: ")
title = input("Enter a title: ")
content = input("Enter a content: ")
status = input("Enter a status: ")
created_date = input("Enter a created date in format dd-mm-yy: ")
issue_date = input("Enter a issue date in format dd-mm-yy: ")

print(username)
print(title)
print(content)
print(status)
print(created_date[:-3])
print(issue_date[:-3])
